name: Lint-check + Style-normalize Python files

on:
  pull_request:
    paths:
      - '.github/workflows/lint.yml'
      - '**.py'


jobs:
  build:
    name:  lint-check and style-normalize Python files
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Lint with flake8 and Reformat with black
      run: |
        make init-lint-and-black
        make lint
        make black
    - name: commit and push if reformatted
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        if git status --short | grep -q '\.py$'; then git add '*.py' && git commit -m "style: reformat" && git push; fi
        
