name: Lint-check + Style-normalize Python files

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/lint.yml'
      - '**.py'
  pull_request:
    paths:
      - '.github/workflows/lint.yml'
      - '**.py'


jobs:
  build:
    name:  lint-check and style-normalize Python files
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Lint with flake8 and Reformat with black
      run: |
        make init
        make lint
        make black
