# This GHA workflow builds a container image and pushes it to GitHub Container Registry.
name: Build and push `nmdc-migration-cli` container image

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    # Docs: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#example-including-and-excluding-paths
    paths:
      - 'db/migrations/cli/**'
      - '!db/migrations/cli/README.md'

# Note: Individual jobs can override this default permission specification as needed.
permissions: {}

env:
  # Detect whether this GHA workflow is being run from a fork or not.
  IS_ORIGINAL_REPO: ${{ github.repository == 'microbiomedata/nmdc-runtime' }}

  # Check whether `github.ref` (i.e. the full reference to the branch or tag that triggered this
  # workflow run) is a tag ref whose name starts with "v".
  IS_PROD_RELEASE: ${{ startsWith(github.ref, 'refs/tags/v') }}

jobs:
  build:
    name: Build image
    permissions: { contents: read, packages: write }
    runs-on: ubuntu-latest
    steps:
      - name: Check out commit
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Install QEMU (an architecture emulator) and buildx (a plugin for the Docker CLI) so that the
      # `docker/build-push-action` action (which we run later) can build both the `linux/amd64` and
      # the `linux/arm64` container images on the same runner.
      #
      # Docs: https://github.com/marketplace/actions/docker-setup-qemu
      # Docs: https://github.com/marketplace/actions/docker-setup-buildx
      #
      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      # Generate tags for the eventual container image.
      - name: Generate image tags
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        # Create annotations on both the image index and on each image's manifest.
        # We do this because, when showing a multi-platform image, GHCR gets the description from
        # the image index, not from the individual image's manifest (for single-platform images,
        # GHCR gets it from the latter).
        # Docs: https://docs.docker.com/build/ci/github-actions/annotations/#configure-annotation-level
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          images: |
            ghcr.io/microbiomedata/nmdc-migration-cli
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=raw,value=prod,enable=${{ env.IS_PROD_RELEASE }}
            type=sha,format=long
          # Note: While we do want the `docker/metadata-action` action to derive values for _some_
          #       labels (e.g. `created`, `revision`); for _other_ labels (listed below), we want to
          #       ensure their values describe `nmdc-migration-cli`, specifically, not `nmdc-runtime`,
          #       in general (as a reminder, the `docker/metadata-action` action derives label values
          #       from the repo in general).
          #
          # References:
          # - https://github.com/docker/metadata-action#overwrite-labels-and-annotations
          # - https://specs.opencontainers.org/image-spec/annotations/#pre-defined-annotation-keys
          #
          labels: |
            org.opencontainers.image.title=nmdc-migration-cli
            org.opencontainers.image.description=Command-line program that migrates the NMDC database between two versions of the NMDC schema
            org.opencontainers.image.documentation=https://github.com/microbiomedata/nmdc-runtime/blob/main/db/migrations/cli/README.md
            org.opencontainers.image.source=https://github.com/microbiomedata/nmdc-runtime/tree/main/db/migrations/cli
            org.opencontainers.image.url=https://github.com/microbiomedata/nmdc-runtime/tree/main/db/migrations/cli

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Docs: https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: db/migrations/cli
          file: db/migrations/cli/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: ${{ env.IS_ORIGINAL_REPO }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
