TARGETS = \
	Description_MIxS_Packages_v5.docx \
	mixs_v4.xlsx \
	mixs_v5.xlsx \
	GOLD-Paths-to-MIxS-ENVO-triad-mapping.xlsx \
	MIxSair_20180621_GOLD_Mapping_04132020.xlsx \
	MIxSbuiltenv_20180621_GOLD_Mapping_04172020.xlsx \
	MIxShostassoc_20180621_GOLD_Mapping.xlsx \
	MIxShumanassoc_20180621_GOLD_Mapping_04142020.xlsx \
	MIxShumangut_20180621_GOLD_Mapping_04152020.xlsx \
	MIxShumanoral_20180621_GOLD_Mapping_04152020.xlsx \
	MIxShumanskin_20180621_GOLD_Mapping_04162020.xlsx \
	MIxShumanvaginal_20180621_GOLD_04162020.xlsx \
	MIxShydrocarbCores_20180621_Mapping_GOLD.xlsx \
	MIxShydrocarbfs_20180621_v5_GOLD_Mapping.xlsx \
	MIxSmatbiofilm_20180621_v5_GOLD_Mapping.xlsx \
	MIxSmisc_20180621_GOLD_Mapping.xlsx \
	MIxSplantassoc_20180621_v5_GOLD_Mapping.xlsx \
	MIxSsediment_20180621_GOLD_Mapping_04102020.xlsx \
	MIxSsoil_20180621_GOLD_Mapping_04102020.xlsx \
	MIxSwastesludge_20180621_GOLD_Mapping_Apr-10.xlsx \
	MIxSwater_20180621_GOLD_Mapping_04122020.xlsx

.PHONY: all clean

all: $(TARGETS)

Description_MIxS_Packages_v5.docx:
	curl -L -s \
	https://docs.google.com/document/d/141BWGbWdTuCQ_QoqdsO_BvHW37wJuLU9xZnvnHTEtNU/export?format=docx \
	> file.tmp && mv file.tmp $@

mixs_v4.xlsx:
	curl -L -s \
	https://docs.google.com/spreadsheets/d/1RJ1bqq7DrCcnpLrlLde4IX8Z7WNT6xjd_NPn8f7tXBU/export?format=xlsx \
	> file.tmp && mv file.tmp $@

mixs_v5.xlsx:
	curl -L -s \
	https://docs.google.com/spreadsheets/d/1P4v7sGSXW4sKWVwOXASYuXxQBWVq7X-ueeiTcoHjLGY/export?format=xlsx \
	> file.tmp && mv file.tmp $@

GOLD-Paths-to-MIxS-ENVO-triad-mapping.xlsx:
	curl -L -s \
		https://docs.google.com/spreadsheets/d/1Tfbj0QCckk_S6ldyVJZcTdJKZHd1D9Y4whWz2CjeIcI/export?format=xlsx \
		> file.tmp && mv file.tmp $@

MIxSair_20180621_GOLD_Mapping_04132020.xlsx:
	curl -L -s \
	https://docs.google.com/spreadsheets/d/1E-XDw-_Gozxf-2eMDRC75VY8HX3UazgsCVGWfOFqi14/export?format=xlsx \
	> file.tmp && mv file.tmp $@

MIxSbuiltenv_20180621_GOLD_Mapping_04172020.xlsx:
	curl -L -s \
	https://docs.google.com/spreadsheets/d/1AYHlxRvBvKLVKLlvPcU_AvhYb_uZTzSgPTVftj47_G0/export?format=xlsx \
	> file.tmp && mv file.tmp $@

MIxShostassoc_20180621_GOLD_Mapping.xlsx:
	curl -L -s \
	https://docs.google.com/spreadsheets/d/1LJzNVDFnT8l-4Ff6h70oMQa3IThVWTaw0IoKwXwcdO0/export?format=xlsx \
	> file.tmp && mv file.tmp $@

MIxShumanassoc_20180621_GOLD_Mapping_04142020.xlsx:
	curl -L -s \
	https://docs.google.com/spreadsheets/d/1TEQIlb33ScABs6fo47UJyW8DrvYAXpJBlbDBY8c1_X8/export?format=xlsx \
	> file.tmp && mv file.tmp $@

MIxShumangut_20180621_GOLD_Mapping_04152020.xlsx:
	curl -L -s \
	https://docs.google.com/spreadsheets/d/15wmnJQbpjqq0vviElDKFGG977vt0P0xWlzlGL0o9ejA/export?format=xlsx \
	> file.tmp && mv file.tmp $@

MIxShumanoral_20180621_GOLD_Mapping_04152020.xlsx:
	curl -L -s \
	https://docs.google.com/spreadsheets/d/1lo59ZAvWnmNXmUIVMUEIscLqiAqfbIcmIL1LU3I8LPQ/export?format=xlsx \
	> file.tmp && mv file.tmp $@

MIxShumanskin_20180621_GOLD_Mapping_04162020.xlsx:
	curl -L -s \
	https://docs.google.com/spreadsheets/d/1q-zm5ChaVrvs2AKMjvZYPnYpHWgZmH8HIfY3MLe3eoo/export?format=xlsx \
	> file.tmp && mv file.tmp $@

MIxShumanvaginal_20180621_GOLD_04162020.xlsx:
	curl -L -s \
	https://docs.google.com/spreadsheets/d/1jgxYakQu_tfk0KvjflYQSJ8F-OVyOP3SRbozUdVn_9g/export?format=xlsx \
	> file.tmp && mv file.tmp $@

MIxShydrocarbCores_20180621_Mapping_GOLD.xlsx:
	curl -L -s \
	https://docs.google.com/spreadsheets/d/1RopUp6uxahqWlsG_Du-3O-DmQuG1clUEKlurZFF4ehQ/export?format=xlsx \
	> file.tmp && mv file.tmp $@

MIxShydrocarbfs_20180621_v5_GOLD_Mapping.xlsx:
	curl -L -s \
	https://docs.google.com/spreadsheets/d/1lrOjUFPkMED31euzd_t8-ADT52kC2ar6qGT2DidySpQ/export?format=xlsx \
	> file.tmp && mv file.tmp $@

MIxSmatbiofilm_20180621_v5_GOLD_Mapping.xlsx:
	curl -L -s \
	https://docs.google.com/spreadsheets/d/125xwy9tzSiks7eT43EcDqG1RVM-zKdWjpF_CZLfdyKo/export?format=xlsx \
	> file.tmp && mv file.tmp $@


MIxSmisc_20180621_GOLD_Mapping.xlsx:
	curl -L -s \
	https://docs.google.com/spreadsheets/d/1xt-ACR93IDisn2q2WYnA0EvAm7iPK_lPoaU6Sejd1ds/export?format=xlsx \
	> file.tmp && mv file.tmp $@

MIxSplantassoc_20180621_v5_GOLD_Mapping.xlsx:
	curl -L -s \
	https://docs.google.com/spreadsheets/d/13ac0mUrutBUptEnTICuxHVae2eGbQVTXGZwJwoZtHOg/export?format=xlsx \
	> file.tmp && mv file.tmp $@

MIxSsediment_20180621_GOLD_Mapping_04102020.xlsx:
	curl -L -s \
	https://docs.google.com/spreadsheets/d/1XWyrPw2BZ94PxQf03uC3aowKj3Y2WWccHuivK1aeU0E/export?format=xlsx \
	> file.tmp && mv file.tmp $@

MIxSsoil_20180621_GOLD_Mapping_04102020.xlsx:
	curl -L -s \
	https://docs.google.com/spreadsheets/d/1Fr2Bq87PCalcNVbg-M7wukTBIAPIC8e0LYQff52KD40/export?format=xlsx \
	> file.tmp && mv file.tmp $@

MIxSwastesludge_20180621_GOLD_Mapping_Apr-10.xlsx:
	curl -L -s \
	https://docs.google.com/spreadsheets/d/1kuTkBl9MHAm2agKARad9_Z3PxbEUUfeDXcLs3u_6vEI/export?format=xlsx \
	> file.tmp && mv file.tmp $@

MIxSwater_20180621_GOLD_Mapping_04122020.xlsx:
	curl -L -s \
	https://docs.google.com/spreadsheets/d/1-7I_2aDCatSru1mYskEi4i0iUEhFKPvH-vChq-E03uk/export?format=xlsx \
	> file.tmp && mv file.tmp $@

make clean:
	rm $(TARGETS)
